INSERT INTO issuing_agencies (name) VALUES
                                        ('Chủ tịch nước'),
                                        ('Quốc hội'),
                                        ('Chính phủ'),
                                        ('Thủ tướng Chính phủ'),
                                        ('Bộ Bưu chính Viễn thông'),
                                        ('Bộ Công an'),
                                        ('Bộ Công Thương'),
                                        ('Bộ Giáo dục và Đào tạo'),
                                        ('Bộ Giao thông Vận tải'),
                                        ('Bộ Kế hoạch và Đầu tư'),
                                        ('Bộ Khoa học và Công nghệ'),
                                        ('Bộ Lao động Thương binh và Xã hội'),
                                        ('Bộ Ngoại giao'),
                                        ('Bộ Nội vụ'),
                                        ('Bộ Nông nghiệp và Phát triển nông thôn'),
                                        ('Bộ Quốc phòng'),
                                        ('Bộ Tài chính'),
                                        ('Bộ Tài nguyên và Môi trường'),
                                        ('Bộ Thông tin và Truyền thông'),
                                        ('Bộ Tư pháp'),
                                        ('Bộ Văn hóa, Thể thao và Du lịch'),
                                        ('Bộ Xây dựng'),
                                        ('Bộ Y tế'),
                                        ('Ngân hàng Nhà nước Việt Nam'),
                                        ('Tổng cục Hải quan'),
                                        ('Tổng cục Thuế'),
                                        ('Tổng cục Tiêu chuẩn Đo lường Chất lượng'),
                                        ('Kho bạc Nhà nước'),
                                        ('Kiểm toán Nhà nước'),
                                        ('Bảo hiểm xã hội Việt Nam'),
                                        ('Uỷ ban Chứng khoán Nhà nước'),
                                        ('Ban Chấp hành Trung ương'),
                                        ('Thanh tra Chính phủ'),
                                        ('Văn phòng Chính phủ'),
                                        ('Văn phòng Quốc hội'),
                                        ('Tòa án nhân dân tối cao'),
                                        ('Viện kiểm sát nhân dân tối cao'),
                                        ('Tổng Liên đoàn Lao động Việt Nam'),
                                        ('Ủy ban nhân dân Thành phố Hà Nội'),
                                        ('Ủy ban nhân dân Thành phố Hồ Chí Minh'),
                                        ('Ủy ban nhân dân Thành phố Đà Nẵng'),
                                        ('Ủy ban nhân dân Thành phố Hải Phòng'),
                                        ('Ủy ban nhân dân Thành phố Cần Thơ');
INSERT INTO fields (name) VALUES
                              ('An ninh quốc gia'),
                              ('An ninh trật tự'),
                              ('Bảo hiểm'),
                              ('Cán bộ-Công chức-Viên chức'),
                              ('Chính sách'),
                              ('Chứng khoán'),
                              ('Cơ cấu tổ chức'),
                              ('Cổ phần-Cổ phần hoá'),
                              ('Công nghiệp'),
                              ('COVID-19'),
                              ('Dân sự'),
                              ('Đất đai-Nhà ở'),
                              ('Đấu thầu-Cạnh tranh'),
                              ('Đầu tư'),
                              ('Địa giới hành chính'),
                              ('Điện lực'),
                              ('Doanh nghiệp'),
                              ('Giáo dục-Đào tạo-Dạy nghề'),
                              ('Giao thông'),
                              ('Hải quan'),
                              ('Hàng hải'),
                              ('Hành chính'),
                              ('Hình sự'),
                              ('Hôn nhân gia đình'),
                              ('Kế toán-Kiểm toán'),
                              ('Khiếu nại-Tố cáo'),
                              ('Khoa học-Công nghệ'),
                              ('Lao động-Tiền lương'),
                              ('Ngoại giao'),
                              ('Nông nghiệp-Lâm nghiệp'),
                              ('Quốc phòng'),
                              ('Sở hữu trí tuệ'),
                              ('Tài chính-Ngân hàng'),
                              ('Tài nguyên-Môi trường'),
                              ('Thi đua-Khen thưởng-Kỷ luật'),
                              ('Thông tin-Truyền thông'),
                              ('Thực phẩm-Dược phẩm'),
                              ('Thuế-Phí-Lệ phí'),
                              ('Thương mại-Quảng cáo'),
                              ('Tiết kiệm-Phòng, chống tham nhũng, lãng phí'),
                              ('Tư pháp-Hộ tịch'),
                              ('Văn hóa-Thể thao-Du lịch'),
                              ('Vi phạm hành chính'),
                              ('Xây dựng'),
                              ('Xuất nhập cảnh'),
                              ('Xuất nhập khẩu'),
                              ('Y tế-Sức khỏe'),
                              ('Lĩnh vực khác');
INSERT INTO document_types (name) VALUES
                                    ('Hiến pháp'),
                                    ('Bộ luật'),
                                    ('Lệnh'),
                                    ('Luật'),
                                    ('Pháp lệnh'),
                                    ('Nghị định'),
                                    ('Nghị quyết'),
                                    ('Quyết định'),
                                    ('Thông tư'),
                                    ('Thông tư liên tịch'),
                                    ('Chỉ thị'),
                                    ('Công văn'),
                                    ('Thông báo'),
                                    ('Công điện'),
                                    ('Hiệp định'),
                                    ('Hiệp ước'),
                                    ('Điều ước quốc tế'),
                                    ('Công ước'),
                                    ('Bản ghi nhớ'),
                                    ('Báo cáo'),
                                    ('Biên bản'),
                                    ('Cam kết'),
                                    ('Chỉ thị liên tịch'),
                                    ('Chương trình'),
                                    ('Đề án'),
                                    ('Điều lệ'),
                                    ('Đính chính'),
                                    ('Giải đáp'),
                                    ('Hiến chương'),
                                    ('Hướng dẫn'),
                                    ('Hướng dẫn liên ngành'),
                                    ('Kế hoạch'),
                                    ('Kế hoạch liên tịch'),
                                    ('Kết luận'),
                                    ('Nghị định thư'),
                                    ('Nghị quyết liên tịch'),
                                    ('Phương án'),
                                    ('Quy chế'),
                                    ('Quy chế phối hợp'),
                                    ('Quy định'),
                                    ('Quy trình'),
                                    ('Sắc lệnh'),
                                    ('Sắc luật'),
                                    ('Sao lục'),
                                    ('Thoả thuận'),
                                    ('Thoả ước'),
                                    ('Thông báo liên tịch'),
                                    ('Thông cáo'),
                                    ('Thông tri'),
                                    ('Thư trao đổi'),
                                    ('Tờ trình'),
                                    ('Tuyên bố chung'),
                                    ('Văn bản hợp nhất'),
                                    ('Ý định thư');
